spring:
  application:
    name: EjerciciosSpring

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Richardson
    username: postgres
    password: a
