spring:
  application:
    name: data2
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/jpa_data_01
    username: postgres
    password: postgres

